name: Meri Wayne Photo
favicon: null
layout_spectrum: 0.16140017565339804
typography_spectrum: 0.0037800129503011703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9980487353168428
  lightness: 0.7861875370144844
  saturation: 0.07453374448232353
  rhythmicContrast: 0.8826764454133809
purpose: []
